# Generated by Django 4.2.2 on 2023-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(max_length=255)),
                ('centreid', models.IntegerField()),
                ('clusterid', models.IntegerField()),
                ('centrepostalcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder', models.IntegerField()),
                ('eldergender', models.CharField(max_length=255)),
                ('nricorfin', models.CharField(max_length=255)),
                ('postalcode1', models.IntegerField()),
                ('postalcode2', models.CharField(max_length=255)),
                ('centre', models.CharField(max_length=255)),
                ('tofromcentre', models.CharField(max_length=255)),
                ('weekday', models.CharField(max_length=255)),
                ('etaetd', models.IntegerField()),
                ('timepickupdeliver', models.IntegerField()),
                ('eldertype', models.CharField(max_length=255)),
                ('elderservicetype', models.CharField(max_length=255)),
                ('caregiver', models.IntegerField()),
                ('loadingtime', models.IntegerField()),
                ('rowid', models.IntegerField(null=True)),
                ('fromtopostal', models.IntegerField(null=True)),
                ('distancekm', models.IntegerField(null=True)),
                ('minn', models.IntegerField(null=True)),
                ('min', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(max_length=255)),
                ('driverid', models.IntegerField()),
                ('drivername', models.CharField(max_length=255, null=True)),
                ('vehicleno', models.IntegerField()),
                ('vehicleid', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(max_length=255)),
                ('vehiclecapacity', models.IntegerField()),
                ('maxwheelchairelder', models.IntegerField()),
                ('maxambulantelder', models.IntegerField()),
                ('maxcaregiver', models.IntegerField()),
            ],
        ),
    ]
